<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [ ]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [ ]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [ ]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[8, 2, 5, 9],
        [6, 1, 6, 0],
        [5, 6, 9, 5]])

In [ ]:
torch.rand(3, 4)

tensor([[0.3196, 0.9387, 0.9268, 0.1246],
        [0.6700, 0.7529, 0.8687, 0.3948],
        [0.2279, 0.2309, 0.0151, 0.0339]])

In [ ]:
torch.randn((3,4))

tensor([[ 1.3746, -0.2895, -0.4134, -1.8711],
        [-0.3113,  0.8154,  0.5902, -0.8436],
        [ 0.8125,  0.3806, -0.5974, -0.6515]])

In [ ]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<IPython.core.display.Javascript object>

<class 'numpy.ndarray'> <class 'torch.Tensor'>
